Remove cdylib from the crate-type as it was generating error during runtime:
Loading native library j4rs from path /home/dimitris/git/rust-keylock-repos/rust-keylock-ui/rust/target/debug/deps
Exception in thread "main" org.astonbitecode.j4rs.errors.InvocationException: Error while invoking method initialize of Class org.astonbitecode.j4rs.api.invocation.NativeCallbackSupport
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeStatic(JsonInvocationImpl.java:66)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeMethod(JsonInvocationImpl.java:135)
	at org.astonbitecode.j4rs.api.invocation.JsonInvocationImpl.invokeStatic(JsonInvocationImpl.java:63)
Caused by: java.lang.UnsatisfiedLinkError: /home/dimitris/git/rust-keylock-repos/rust-keylock-ui/rust/target/debug/deps/libj4rs.so: /home/dimitris/git/rust-keylock-repos/rust-keylock-ui/rust/target/debug/deps/libj4rs.so: undefined symbol: __rust_realloc
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.astonbitecode.j4rs.api.invocation.NativeCallbackSupport.initialize(NativeCallbackSupport.java:34)
	... 6 more
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JavaError("An Exception was thrown by Java while creating global ref... Please check the logs or the console.")', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.